### ISSUE TITLE
现在进度如何？可以参与进来吗？

### ISSUE THREAD

**Issue by bgdsh** [ts-believers/learning-typescript-sample#3]
我是一个后端工程师，以Node.js为主；Typescript的爱好者；订阅了一年的Packt pub的会员。
我可以参与到这个项目里面吗？ 翻译某个章节或者是帮忙校正都可以。我曾经试着翻译了一本[《Node.js设计模式》](https://github.com/bgdsh/NodeJSDesignPatternZh_CN) 。期待回复。

**Comment by Brooooooklyn** [comment]
谢谢关注，已经出版了
https://item.jd.com/12001593.html

**Comment by bgdsh** [comment]
干得漂亮，哈哈哈哈。
